name: Release project

on:
  push:
    branches:
      - main

# Limit token permissions for security
permissions: read-all

jobs:
  publish-zenodo:
    # uses: ./.github/workflows/reusable-publish-zenodo-file.yml@main
    uses: ./.github/workflows/reusable-publish-zenodo-file.yml
    with:
      use_sandbox: true
    secrets:
      zenodo-token: ${{ secrets.ZENODO_SANDBOX_TOKEN }}
